-- ==========================================
-- forSeller AI MVP 카카오 알림톡 자동화 데이터베이스 DDL 스키마 설계서
-- 
-- 사용 방법: Supabase 대시보드 -> SQL Editor -> New Query 진입 후 
-- 아래 DDL 스크립트 전체를 그대로 복사하여 붙여넣고 [Run] 버튼을 누르시면 
-- 1초 만에 최적의 테이블 및 전송 큐 자동화 트리거가 완성됩니다.
-- ==========================================

-- 1. 파트너 셀러 회원 추가 프로필 테이블 (Profiles)
-- (기본 Supabase auth.users와 1:1 연동되며, 가입 시 입력받은 전화번호 및 관심 카테고리를 저장합니다.)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    phone TEXT NOT NULL,
    category TEXT DEFAULT '의류',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS (Row Level Security) 설정 - 본인 프로필만 수정 가능
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "로그인한 사용자는 본인 프로필만 조회 가능" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "로그인한 사용자는 본인 프로필만 삽입 가능" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "로그인한 사용자는 본인 프로필만 수정 가능" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. 매일 아침 발송할 소싱 추천 상품 데이터 테이블 (kakao_reports)
CREATE TABLE IF NOT EXISTS public.kakao_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    send_date DATE DEFAULT CURRENT_DATE UNIQUE NOT NULL, -- 발송일자 (하루에 단 1개의 공식 리포트만 UNIQUE)
    
    -- 상품 1 상세 통계
    prod_1_title TEXT NOT NULL,
    prod_1_wholesale INT NOT NULL,
    prod_1_retail INT NOT NULL,
    prod_1_margin INT NOT NULL,
    prod_1_emoji TEXT DEFAULT '🔦',
    
    -- 상품 2 상세 통계
    prod_2_title TEXT NOT NULL,
    prod_2_wholesale INT NOT NULL,
    prod_2_retail INT NOT NULL,
    prod_2_margin INT NOT NULL,
    prod_2_emoji TEXT DEFAULT '🧹',
    
    -- 상품 3 상세 통계
    prod_3_title TEXT NOT NULL,
    prod_3_wholesale INT NOT NULL,
    prod_3_retail INT NOT NULL,
    prod_3_margin INT NOT NULL,
    prod_3_emoji TEXT DEFAULT '💧',
    
    -- AI 정밀 진단 한줄 분석 소견
    ai_diagnosis TEXT NOT NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. 실시간 알림톡 발송 대기 큐 테이블 (kakao_sending_queue)
CREATE TABLE IF NOT EXISTS public.kakao_sending_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT REFERENCES public.kakao_reports(id) ON DELETE CASCADE NOT NULL,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    
    receiver_name TEXT NOT NULL,         -- 사장님 명칭 (이메일 아이디 또는 성함)
    receiver_phone TEXT NOT NULL,        -- 발송될 전화번호 (010-XXXX-XXXX)
    
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')) NOT NULL, -- 발송 상태
    sent_at TIMESTAMP WITH TIME ZONE,    -- 실제 발송 성공 시간
    error_message TEXT,                  -- 발송 실패 시 대행사 에러 로그
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. [자동화 핵심 트리거] 
-- 매일 아침 8시 관리자가 'kakao_reports'에 새로운 그날의 황금 상품 추천 데이터를 입력(INSERT)하면, 
-- 현재 가입되어 있는 모든 활성 파트너 셀러(profiles) 목록을 자동으로 긁어와 
-- 발송 큐(kakao_sending_queue)에 실시간 대량 인서트 적재하는 트리거 PL/pgSQL 함수입니다.

CREATE OR REPLACE FUNCTION public.fn_enqueue_kakao_reports()
RETURNS TRIGGER AS $$
BEGIN
    -- 현재 profiles 테이블에 가입되어 있는 모든 파트너 셀러들을 발송 큐에 일괄 적재
    INSERT INTO public.kakao_sending_queue (
        report_id,
        profile_id,
        receiver_name,
        receiver_phone,
        status
    )
    SELECT 
        NEW.id,
        p.id,
        split_part(p.email, '@', 1), -- 이메일 골뱅이 앞자리를 사장님 닉네임/아이디로 자동 매칭
        p.phone,
        'pending'
    FROM 
        public.profiles p;
        
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- kakao_reports 테이블에 INSERT가 발생한 직후 트리거 함수 가동 설정
CREATE OR REPLACE TRIGGER tr_enqueue_kakao_reports
AFTER INSERT ON public.kakao_reports
FOR EACH ROW
EXECUTE FUNCTION public.fn_enqueue_kakao_reports();
